Templates must be inline with the internal repo
IBM/ibm-vpc-block-csi-driver pull request #6
Opened 2021-06-21 09:34 UTC by ambiknai

2021-06-21 09:51 UTC, meghnasiingh submitted a review, later dismissed

2021-06-21 10:24 UTC, arahamad requested changes
Can you do that changes

2021-06-21 10:24 UTC, arahamad commented on deploy/kubernetes/driver/kubernetes/manifests/controller-server.yaml
> +        - name: storage-secret-sidecar
Opensource lib should not have sidecar related changes, can you remove all sidecar related reference

2021-06-21 14:04 UTC, arahamad approved these changes
LGTM

2021-06-22 06:14 UTC, sameshai approved these changes

2021-06-22 06:17 UTC, meghnasiingh approved these changes

2021-06-22 06:34 UTC, arahamad approved these changes
LGTM

2021-06-22 06:37 UTC, merged